### ISSUE TITLE
Lunch and Learn

### ISSUE THREAD

**Issue by johnsiwicki** [bs-production/front-end-guidelines#11]
We need a topic for May?

**Comment by johnsiwicki** [comment]
Cool Screencasts: 
Getting More from Analytics - https://www.youtube.com/watch?v=jSHqlFkJiBI
ReactJs - https://www.youtube.com/watch?v=LR_Fb2LbnhY

**Comment by Kingpinesse** [comment]
**_This is cool thanks John_**

**Comment by chrisroselli** [comment]
Nice. The man himself, Chris Coyier.

**Comment by johnsiwicki** [comment]
Our teacher lied, I am still getting email

**Comment by chrisroselli** [comment]
# Ha
- I turned mine off
- [ ] We'll see
  :clap:
  http://www.emoji-cheat-sheet.com/
  Type a colon and watch your emojis go.

**Comment by johnsiwicki** [comment]
Google I/O Videos : https://www.youtube.com/playlist?list=PLNYkxOF6rcIDz1TzmmMRBC-kd8zPRTQIP

Web Accessibility : https://webaccessibility.withgoogle.com/course
