### ISSUE TITLE
Tasks Made For Programming

### ISSUE THREAD

**Issue by johnsiwicki** [bs-production/front-end-guidelines#16]
- [ ]  Get a Development System For Borders/CSS
- [ ]  System To Push Core changes live
- [ ] New Core Token For New Template
- [ ] Logos From portal into site templates.
- [ ] Improve CMS Link Checker. 
- [x] Make Custom Template Workout Outside The building
- [ ] CMS Top Nav / Footer Builder

**Comment by johnsiwicki** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;roAhQ7ep&#x2F;10-we-did-it-180-sites"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> We Did It 180 sites</a>

**Comment by supert3d** [comment]
Congratz!
