### ISSUE TITLE
About Us Supernav

### ISSUE THREAD

**Issue by figdesigns** [bs-production/front-end-guidelines#35]
Custom array snippets not working.
Example: http://www.carlsoncgc.com/?cache=0&dev_template=1

    //Replace With Page ID of Financing Page
    131004 => array(
        'grandchildren' => false
    ),
    //Replace with Page ID of Reviews Page
    133759 => array(
        'grandchildren' => false
    ),

**Comment by johnsiwicki** [comment]
Task Made For This
