### ISSUE TITLE
Site Speed Project - Every Site to Green

### ISSUE THREAD

**Issue by johnsiwicki** [bs-production/front-end-guidelines#39]
- Minify / Combine Rackspace Files 
- How to load JS/CSS

Make a Task for programming
~~Cache Headers for Amazon s3 images~~
~~Compression levels~~

**Comment by johnsiwicki** [comment]
[idea.txt](https://github.com/bs-production/front-end-guidelines/files/1145057/idea.txt)

have it upload the output to rackspace and then ?build=test url parameter

**Comment by kevflan** [comment]
Test page I was working on.
http://devtest22.basementsite.com/idea.html?cache=0

**Comment by johnsiwicki** [comment]
https://deploybot.com/

**Comment by johnsiwicki** [comment]
https://www.sitelocity.com/critical-path-css-generator

**Comment by johnsiwicki** [comment]
widget arrows on mobile.

**Comment by johnsiwicki** [comment]
no swipes on mobile

**Comment by johnsiwicki** [comment]
@chrisroselli just trying something nothing to see here
