### ISSUE TITLE
Widget not showing in Widgets & Modules sidenav

### ISSUE THREAD

**Issue by Kingpinesse** [bs-production/front-end-guidelines#55]
Example:
Content management of http://cobarroofing.basementsite.com/tx.html
The widget or module are not showing up in the Widgets & Modules sidenav when the Body Content is check to show in Work in HTML Mode.
This is very frustrating, as I have to remove my content and only show the widget; check off Work in HTML Mode > Save and now I can see it in the Body Content for edit. This is cheesing crazy man.

**Comment by johnsiwicki** [comment]
Single page landing page is the issue 

Regan home page https://www.contractornation.com/app/?module=cms_content&action=edit&id=150235&select_site=1481&prevreq=598cbed5d735b

**Comment by johnsiwicki** [comment]
programming task made
