### ISSUE TITLE
Custom Items in Supernav not displaying when using SplitAboutWork

### ISSUE THREAD

**Issue by figdesigns** [bs-production/front-end-guidelines#57]
Adding "$superNav->superSplitAboutWork = true;" markup blocks custom nav items from displaying. 

**Example (this works perfect):**
<?php
    $superNav = new nav();
    $superNav->superMode = 'top';
    $superNav->superItems = array(
        'Services' => array(
            'target' => 'services'
        ),
        'Our Work' => array(
            'target' => 'about',
            'show_about_link' => false
        ),
        'Service Area' => array(
            'target' => 'map',
        ),
        //Replace with Page ID of Job Opportunities -- THIS DISPLAYS CUSTOM ITEM
        70655 => array(
            'grandchildren' => false
        ),
        'Free Quote' => array(
            'class' => 'quote',
            'target' => 'contact'
        )
    );
    echo $superNav->generateSuperMarkup();
?>

**This does not display custom item:**
<?php
    $superNav = new nav();
    $superNav->superMode = 'top';
    $superNav->superSplitAboutWork = true;  // ADDED FOR SPLIT
    $superNav->superItems = array(
        'Services' => array(
            'target' => 'services'
        ),
        'Our Work' => array(
            'target' => 'work',
        ),
        17728 => array(
            'target' => 'about',
            'show_about_link' => false
        ),
        'Service Area' => array(
            'target' => 'map',
        ),
        //Replace with Page ID of Job Opportunities -- DOES NOT DISPLAY ANYMORE
        70655 => array(
            'grandchildren' => false
        ),
        'Free Quote' => array(
            'class' => 'quote',
            'target' => 'contact'
        )
    );
    echo $superNav->generateSuperMarkup();
?>

**Comment by chrisroselli** [comment]
Also causing issues with mobile nav
