### ISSUE TITLE
Overlay NEEDs to be fixed

### ISSUE THREAD

**Issue by Kingpinesse** [bs-production/front-end-guidelines#62]
The overlay on pages is so helpful when you just want to go and fix something on a page without searching through the WHOLE content management (ex. Thrasher) it would be really helpful if this was working again.

**Comment by johnsiwicki** [comment]
Is there a part that is breaking?

**Comment by Kingpinesse** [comment]
Yes it shows at the bottom and no buttons to lead you to the page.

**Comment by johnsiwicki** [comment]
ok, thank you
