### ISSUE TITLE
Broadcast widget

### ISSUE THREAD

**Issue by chrisroselli** [bs-production/front-end-guidelines#77]
Broadcast widget needs redesigning for all use cases.

**Comment by chrisroselli** [comment]
Same with "View Live Site"

**Comment by johnsiwicki** [comment]
@chrisroselli Can you give me more?

**Comment by chrisroselli** [comment]
Broadcast widget will sometime overlap header, especial on custom headers when dealer activates a broadcast after design is complete. Next time I see it, I will  itemize notes for a solution.

**Comment by johnsiwicki** [comment]
https://www.american-waterworks.com/   @chrisroselli

**Comment by chrisroselli** [comment]
Excellent example.
